sudo: required

services:
  - docker

branches:
  only:
    - master
    - /^v\d+/

script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ./build.sh; fi

deploy:
  provider: bintray
  file: bintray-descriptor.json
  user: $BINTRAY_USERNAME
  key: $BINTRAY_APIKEY
  skip_cleanup: true  
